wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.2
    framework: huggingface
    huggingface_version: 4.12.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1634723479
    t:
      1:
      - 1
      - 11
      2:
      - 1
      - 11
      3:
      - 13
      4: 3.8.5
      5: 0.12.2
      6: 4.12.0.dev0
      8:
      - 5
